### DISCUSSION TITLE
Pylance shows linting errors from excluded folders

### DISCUSSION THREAD

**Discussion by WizzyGeek** [microsoft/pylance-release#1883] [Q&A] [answered]
# About

I use a local `.venv` folder for my project's virtual environment. As stated in Pyright config docs I excluded that folder in `pyproject.toml` yet Pylance keeps linting `.venv/**` files

## Related Config
```toml
[tool.pyright]
include = ["uprate"]
exclude = ["docs", ".venv", ".git", "**/__pycache__", ".mypy_cache"]
```

Do I need to configure Pylance to use a `pyproject.toml` file? if yes, how?
