### ISSUE TITLE
Pylance not using pyproject.toml

### ISSUE THREAD

**Issue by Ierezell** [microsoft/pylance-release#1449]
<h3> Environment data </h3>

-   Language Server version: 2021.6.2-pre.1 (pyright e3f7cccc)
-   OS and version: linux x64 5.12.9
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.5
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: undefined

<h3> Expected behaviour </h3>

Use the config in `pyproject.toml` to configure pylance (note I also tried tool.pylance)

```toml
[tool.pyright]
root = ['src']
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]

useLibraryCodeForTypes = true

strict = ["src"]
typeCheckingMode = "strict"

reportMissingImports = "information"
reportMissingTypeStubs = "information"
reportUnknownMemberType = "information"
```

I also tried with  (and also tool.pylance)
```toml
[[tool.pyright.overrides]]
reportMissingImports = "information"
reportMissingTypeStubs = "information"
reportUnknownMemberType = "information"
```
<h3> Actual behaviour </h3>

Still reporting missing stub and other as errors instead of informations

<h3> Logs </h3>

Python Language Server Log
I Added a text file as the body was too long for the logs.
  
Thanks in advance for any help, 

Have a great day 

[logs.txt](https://github.com/microsoft/pylance-release/files/6649852/plop.txt)

**Comment by erictraut** [comment]
The top example looks (mostly) correct to me. There is no supported config key called "root", but the rest should work fine. I just tried it with Pylance, and it worked fine for me.

Do you have the "pyproject.toml" at the root of your workspace?

Do you have a "pyrightconfig.json" file present? It takes precedent over "pyproject.toml".

**Comment by Ierezell** [comment]
Hi @erictraut, 

Thanks for your fast answer, 

I have the `pyproject.toml` at the root of the workspace (and removed root key just in case). 
I do not have a `pyrightconfig.json` however I have a `.vscode/settings.json` file (with exactly the same config). I tried to remove it but it doesn't change anything. 

I still got `reportMissingStub` error in the `Problem`  tab of vscode instead of information. 
![image](https://user-images.githubusercontent.com/30974685/121938014-4cb8fb80-cd19-11eb-9714-8789e3bcf36c.png)

with the config : 
```toml

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]

useLibraryCodeForTypes = true

strict = ["src"]
typeCheckingMode = "strict"

reportMissingImports = "information"
reportMissingTypeStubs = "information"
reportUnknownMemberType = "information"

extraPaths = [
    "src",
    "__pypackages__/3.9/lib"
]
```

no `settings.json` nor `pyrightconfig.json`

Thanks for your help,
