### ISSUE TITLE
Pylance analysing all pypackages folder

### ISSUE THREAD

**Issue by Ierezell** [microsoft/pylance-release#1455]
Hi, 

I was trying the new standards with `pyproject.toml` and `__pypackages__` (using pdm).

However, when pdm install all my dependencies in the `__pypackages__` folder I got two problems : 
- vscode is not importing packages and I need to specify extraPaths in python.analyzing.extraPaths. Could it be done by default like with the .venv folders ? 
- Pylance is analyzing all the pypackages folder (10K+ files) which makes the UI almost freezing also errors in those packages are logged as errors in the problem tab 100K+ errors !).

I managed to configure pyright in `pyporject.toml` as 

```toml
[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]

useLibraryCodeForTypes = true

strict = ["src"]
typeCheckingMode = "strict"

reportMissingImports = "information"
reportMissingTypeStubs = "information"
reportUnknownMemberType = "information"

extraPaths = ["src"]
```

Which helps to remove all the pypackages linting however all the missing stubs still appear as errors...

Also even with adding pypackages in the extraPaths some modules are recognized and I got no import errors but some others aren't recognized and I got  `import could not be resolved errors`

Note : I also have this config in `.vscode/settings.json` but still same errors. 

```json
{
    "python.analysis.autoImportCompletions": true,
    "python.analysis.autoSearchPaths": true,
    "python.analysis.diagnosticMode": "workspace",
    "python.autoComplete.extraPaths": ["__pypackages__/3.9/lib",  "src" ],
    "python.analysis.extraPaths": ["__pypackages__/3.9/lib", "src"],
    "python.analysis.diagnosticSeverityOverrides": {
        "reportUnknownMemberType": "information",
        "reportMissingTypeStubs": "information"
    },
    "python.diagnostics.sourceMapsEnabled": true,
    "python.analysis.typeCheckingMode": "strict",
    "python.languageServer": "Pylance",
}
```

I guess more and more people will start to use the new norms, is there a plan to support all those new pep ? 

Thanks in advance 
Have a great day
