### ISSUE TITLE
Define "known first party" for imports

### ISSUE THREAD

**Issue by MinchinWeb** [microsoft/pylance-release#1542]
For isort, I can define a set of "known first party imports":

```toml
# pyproject.toml

[tool.isort]
known_first_party = ["battlestation", "minchin"]
```

However, pylance isn't recognizing this setting, and I can find no way to set it myself.

![image](https://user-images.githubusercontent.com/1548809/125144355-d4a4e200-e0da-11eb-8736-7a4787ddce6b.png)

So how do I set "first party" modules for import in pylance?
