### ISSUE TITLE
BUG: Incorrect Warnings for 'Unnecessary "# type: ignore" comment'

### ISSUE THREAD

**Issue by adam-grant-hendry** [microsoft/pylance-release#2943]
## Environment data

-   Language Server version: v2022.6.11 (Pre-Release)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.10 (CPython implementation)

## Code Snippet

After placing a type ignore on the following `pylance` error

![image](https://user-images.githubusercontent.com/59346180/173942126-6b78ab1b-c491-4b3d-9693-2a8f8cfd4e4e.png)

`pylance` incorrectly warns that the type ignore is redundant:

![image](https://user-images.githubusercontent.com/59346180/173942229-4f559477-3382-4c3a-b96e-917775816cf3.png)

The same behavior occurs with all errors attempted to be ignored, regardless of whether the syntax is `# pyright: ignore` or `# type: ignore`.

## Repro Steps

`mypy 0.961` is being run in `vscode 1.68.1`. The project uses a `pyproject.toml` with the following `mypy` settings:

```toml
[tool.mypy]
python_executable = ".venv/Scripts/python.exe"
python_version = "3.8"
disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
show_error_codes = true
exclude = [
    '.venv/',
    'logs',
    'build',
    'dist'
]
files = [
    'myproj',
    'docs',
    'resources',
    'tests'
]
no_pretty = true
show_column_numbers = true
```

and a user (global) level `settings.json` configured to run the `dmypy.exe` daemon:

```json
{
    "mypy.dmypyExecutable": "${workspaceFolder}/.venv/Scripts/dmypy.exe",
    "python.analysis.diagnosticSeverityOverrides": {
        "reportPrivateImportUsage": "information",
        "reportUnnecessaryTypeIgnoreComment": "information"
    },
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/Scripts/python.exe",
    "python.linting.mypyArgs": [
        "--config-file",
        "pyproject.toml"
    ],
    "python.linting.mypyEnabled": true,
    "python.linting.mypyPath": "${workspaceFolder}/.venv/Scripts/mypy.exe",
}
```

## Expected behavior

`pylint` only warns about `unnecessary type ignore`s when removing them will actually not yield an error (i.e. they are actually unnecessary).

## Update

This may not be a bug if this is expected behavior when

```json
"python.analysis.diagnosticSeverityOverrides": {
    "reportUnnecessaryTypeIgnoreComment": "information"
},
```

is used. However, perhaps these are conflicting settings when used in conjunction?
