### ISSUE TITLE
Pyright and pylance disagree

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/pylance-release#4163]
## Environment data

-   Language Server version: Pylance language server 2023.3.30 (pyright 68a8e98a) and `pyright -> 1.1.301`
-   OS and version: windows 11 (22621)
-   Python version (& distribution if applicable, e.g. Anaconda): `3.11.1`

## Code Snippet

![image](https://user-images.githubusercontent.com/6558089/228525176-4e26f900-4968-4ebb-9c0f-a563ffa3145d.png)
`pyright -> 1.1.301` in CI and over the cli don't complain
`matplotlib -> 3.7.1`
`pylance -> v2023.3.30`

## Additional info
Other editors (e.g. helix) configured with pyright as lsp server are in sync with pyright's view of the world and don't have this issue, that's why I suspect something going on in _vscode_ with  _pylance_

I also think this issue has nothing to do with the latest release pyright, we have seen this a couple of times in the past  weeks with older versions of pyright too.
## Repro Steps
See [here](https://github.com/microsoft/pylance-release/issues/4163#issuecomment-1489917429)

## Expected behavior

Pyright when called over the cli and editing code in vscode (pylance) report the same issues

## Actual behavior

Pyright and pylance disagree

## Logs

```
TODO: do upon request if needed.
```

**Comment by erictraut** [comment]
@judej, can we please prioritize [this issue](https://github.com/microsoft/pylance-release/issues/4085)? Documentation is badly needed here.

**Comment by FrancescElies** [comment]
ℹ️ On our side we are working on a reprex, if we are lucky by tomorrow we might be able to provide it

**Comment by FrancescElies** [comment]
Current workaround for us was to set `reportUnnecessaryTypeIgnoreComment = false`

**Comment by erictraut** [comment]
@FrancescElies, it looks like you're not setting `useLibraryCodeForTypes` in your pyproject.toml. If left unspecified, this setting defaults to `false` in pyright but `true` in pylance. I recommend that you explicitly set it to `false` in your pyproject.toml.

**Comment by rchiodo** [comment]
I'm currently working on the documentation. Hope to have something for review today.

**Comment by rchiodo** [comment]
See the linked PR. Comments welcome

**Comment by FrancescElies** [comment]
@erictraut sorry for my late reply, I just tried your `useLibraryCodeForTypes` suggestion (see pyproject.toml below) but as soon as I activate `reportUnnecessaryTypeIgnoreComment=true` vscode complains, for the time being we will leave it as `reportUnnecessaryTypeIgnoreComment=false`.

In the next days I will read @rchiodo's update (thanks for that) [USING_WITH_PYRIGHT.md](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md) and probably we will end up copying stubs from vscode's dist folder if we feel like activating `reportUnnecessaryTypeIgnoreComment=true` again.


<details>
  <summary>pyproject.toml (Click me)</summary>
  

  ### Some Code
  ```toml
	[tool.pyright]
	# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
	include = ["."]
	typeCheckingMode = "strict"
	useLibraryCodeForTypes = true

	# Despite of pyright's sctrict defaults check the following:
	strictListInference = true
	strictDictionaryInference = true
	strictSetInference = true
	analyzeUnannotatedFunctions = true
	strictParameterNoneValue = true
	enableTypeIgnoreComments = true
	reportMissingModuleSource = true
	reportMissingImports = true
	reportUndefinedVariable = true
	reportAssertAlwaysTrue = true
	reportInvalidStringEscapeSequence = true
	reportInvalidTypeVarUse = true
	reportMissingTypeStubs = true
	reportSelfClsParameterName = true
	reportUnsupportedDunderAll = true
	reportUnusedExpression = true
	reportWildcardImportFromLibrary = true
	reportGeneralTypeIssues = true
	reportOptionalSubscript = true
	reportOptionalMemberAccess = true
	reportOptionalCall = true
	reportOptionalIterable = true
	reportOptionalContextManager = true
	reportOptionalOperand = true
	reportTypedDictNotRequiredAccess = true
	reportPrivateImportUsage = true
	reportUnboundVariable = true
	reportUnusedCoroutine = true
	reportConstantRedefinition = true
	reportDeprecated = true
	reportDuplicateImport = true
	reportFunctionMemberAccess = true
	reportImportCycles = true
	reportIncompatibleMethodOverride = true
	reportIncompatibleVariableOverride = true
	reportIncompleteStub = true
	reportInconsistentConstructor = true
	reportInvalidStubStatement = true
	reportMatchNotExhaustive = true
	reportMissingParameterType = true
	reportMissingTypeArgument = true
	reportOverlappingOverload = true
	reportPrivateUsage = true
	reportShadowedImports = true
	reportTypeCommentUsage = true
	reportUnknownArgumentType = true
	reportUnknownLambdaType = true
	reportUnknownMemberType = true
	reportUnknownParameterType = true
	reportUnknownVariableType = true
	reportUnnecessaryCast = true
	reportUnnecessaryComparison = true
	reportUnnecessaryContains = true
	reportUnnecessaryIsInstance = true
	reportUnusedClass = true
	reportUnusedImport = true
	reportUnusedFunction = true
	reportUnusedVariable = true
	reportUntypedBaseClass = true
	reportUntypedClassDecorator = true
	reportUntypedFunctionDecorator = true
	reportUntypedNamedTuple = true
	reportCallInDefaultInitializer = true
	reportImplicitStringConcatenation = true
	reportPropertyTypeMismatch = true
	reportUninitializedInstanceVariable = true
	reportUnusedCallResult = true
	reportUnnecessaryTypeIgnoreComment = true

	# Disabled  - (add a NOTE for each disabled check)
	# --------
	#
	# NOTE: reportMissingSuperCall doesn't add much value to our codebase and forces
	#       us to make the linter happy on classes without inheritance that are
	#       totally fine without a super-call.
	reportMissingSuperCall = false


	# NOTE: files in the exclude paths may still be included in the analysis if
	#       they are referenced (imported) by source files that are not excluded
	exclude = [
	    ".git",
	    "**/__pycache__",
	    "**/.mypy_cache",
	    "**/venv",
	]
	stubPath = "./typings"
	# Note: files whose diagnostic output (errors and warnings) should be suppressed
	#       even if they are an included file
	ignore = [
	    # autogenerated grpc files
	    "**/*_pb2*",
	    "typings",
	]

	pythonVersion = "3.11"
	pythonPlatform = "Windows"
	stats = true
	warnings = true
	executionEnvironments = [
	  { root = "." }
	]


  ```
</details>
