### ISSUE TITLE
Subtype (`numpy.float64`) is reported as incompatible with parent type (`float`)

### ISSUE THREAD

**Issue by simonaltrogge** [microsoft/pylance-release#4332]
See also numpy/numpy#23663

## Environment data

-   Language Server version: **v2023.5.10**
-   OS and version: **Ubuntu 22.04.2 LTS**
-   Python version (& distribution if applicable, e.g. Anaconda): **3.11.3 Miniconda**
-   numpy version: **1.24.3**
-   python.analysis.indexing: **true**
-   python.analysis.typeCheckingMode: **basic**

### environment.yml

```yml
name: consolidation
channels:
  - conda-forge
  - defaults
dependencies:
  - black=23.3
  - bottleneck=1.3
  - ipywidgets=8.0
  - jupyterlab=3.6
  - matplotlib=3.7
  - netcdf4=1.6
  - numpy=1.24
  - pandas=2.0
  - python=3.11
  - scipy=1.10
  - seaborn=0.12
  - tqdm=4.65
  - xarray=2023.4
  - pip=23.1
  - pip:
      - bctpy==0.6
```

## Code Snippet

```python
import numpy as np

def idx(x: float) -> float:
    return x

arr = np.arange(5.0, dtype=np.float64)
sum = np.sum(arr)
idx(sum)
```

## Repro Steps

1. Create an environment using the provided environment.yml file
2. Open VSCode
3. Create a new Python file
4. Select the newly created environment as interpreter
5. Enter the provided [code snippet](##code-snippet)

## Expected behavior

I would expect Pylance to not give any error messages for the above [code snippet](#code-snippet), as `np.float64` is a subtype of python's native `float` type.

## Actual behavior

Pylance reports the following error message:

```shell
Argument of type "float64" cannot be assigned to parameter "x" of type "float" in function "idx"
  "float64" is incompatible with "float" Pylance (reportGeneralTypeIssues)
```

## Logs

[Python Language Server.log](https://github.com/microsoft/pylance-release/files/11432687/Python.Language.Server.log)
