### ISSUE TITLE
Configuration for numpy

### ISSUE THREAD

**Issue by shaunc** [microsoft/pylance-release#5307]
Pylance is not recognizing arithmetic using numpy types:

![image](https://github.com/microsoft/pylance-release/assets/193170/e732deb8-d756-4b37-b2da-993b46b80f1d)

I am using numpy 1.26.1, pylance v2023.12.1 and python 3.11.

I am using "strict" checking - I assume that that should be possible.

As others are not getting this error, I assume there is something strange about my configuration.  I use mypy in pre-commit to check these errors, and have mypy config in pyproject.toml:
```toml

[tool.mypy]
allow_untyped_calls = false
follow_imports = "skip"
ignore_missing_imports = true
plugins = "numpy.typing.mypy_plugin"
python_version = "3.11"
```

Does pylance require to be told about the (equivalent of?) the mypy_plugin for numpy, and if so, how do I configure it? 

Or perhaps the problem is a cache somewhere? This used to work, before stopping at some point.
