### ISSUE TITLE
Split pyright typechecking include from pylance indexing include

### ISSUE THREAD

**Issue by jvacek** [microsoft/pylance-release#6037]
Somewhat related to https://github.com/microsoft/pylance-release/issues/5969, we didn't know that pylance will use the list of directories pyright uses to typecheck.

We've got a repo where we want to typecheck only certain directories as we want to slowly type everything dir by dir, but we do not want to lose the indexing capabilities for all the folders that are not yet included in indexing

Ideally, it would be nice to have a separate setting for indexing that can override the pylance typechecking dirs.

With an example:

In a repo where pyproject.toml is specified as
```toml
[tool.pyright]

# We are gradually checking the types in this code base.
# Add the directories you want to type check to this list.
include = [
    "foo/",
]
```
and the project structure is 
```
repo
├── bar
│   ├── c.py
│   └── d.py
└── foo
    ├── a.py
    └── b.py
```
you could set pylance to index the entire repo with something like
```json
{
  "python.indexing.include" : [
    "{workspacedir}",
  ]
}
```
so that the total number of files index is 4 (a, b, c, d), and not 2 (a, b)
