### ISSUE TITLE
Pylance fails to resolve imports from virtualenv site-packages unless extraPaths is set

### ISSUE THREAD

**Issue by bilzard** [microsoft/pylance-release#7083]
## Environment data

-   Pylance version: 2025.3.104
-   OS and version: Ubuntu 22.04.4 LTS (DevContainer & Docker)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.12 (via venv)

## Code Snippet

```python
# src/main.py

import somepackage  # Package is installed in .venv but marked as unresolved
```

## Repro Steps

1. Create a virtual environment in `.venv/`:
   ```bash
   python3.10 -m venv .venv
   . .venv/bin/activate
   pip install somepackage
   ```
2. Use the following project structure:
   ```
   project-root/
   ├── .venv/
   ├── src/
   │   └── main.py
   ├── .vscode/
   │   └── settings.json
   └── pyproject.toml
   ```
3. VS Code `.vscode/settings.json`:
   ```json
   {
       "[python]": {
           "editor.defaultFormatter": "charliermarsh.ruff",
           "editor.formatOnSave": true,
           "editor.codeActionsOnSave": {
               "source.organizeImports": "explicit"
           },
           "editor.formatOnType": true,
           "editor.pasteAs.enabled": false
       },
       "editor.codeActionsOnSave": {
           "source.organizeImports": "explicit"
       },
       "python.envFile": "${workspaceFolder}/.env",
       "terminal.integrated.env.linux": {
           "PYTHONPATH": "${workspaceFolder}/src",
       },
       "ruff.importStrategy": "fromEnvironment",
       "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python",
   }
   ```
4. `pyproject.toml`:
   ```toml
   [tool.pyright]

   executionEnvironments = [
       { root = "src", pythonVersion = "3.10", venv = ".venv" },
   ]
   extend_exclude = ["*.ipynb"]
   include = ["src"]
   exclude = [
       "**/node_modules",
       "**/__pycache__",
       "data",
       "src/experimental",
       "src/typestubs",
       "external",
       "log",
   ]
   extraPaths = [
       #".venv/lib/python3.10/site-packages",
   ] # Workaround for pyright not finding packages in .venv
   ignore = []
   defineConstant = { "DEBUG" = true }
   venvPath = "."
   reportMissingImports = "error"
   reportMissingTypeStubs = false
   stubPath = "src/stubs"
   ```
5. `.env`:
    ```env
    PYTHONPATH=${PROJECT_ROOT}/src
    ```

5. Open `main.py` and confirm that Pylance reports a missing import, even though the package is installed in `.venv/lib/python3.10/site-packages`.

## Expected behavior

Pylance should automatically include `.venv/lib/python3.10/site-packages` in the search paths based on the interpreter set in the workspace.

## Actual behavior

The interpreter is set to `.venv/bin/python`, but `site-packages` is not included in the search paths, and imports from installed packages fail.

## Logs

Relevant trace log output (trimmed):

```python
from Bio.PDB import PDBIO, PDBParser, Select  # Package is installed in .venv but marked as unresolved
```

```
"PDBIO" is not exported from module "Bio.PDB"
  Import from "Bio.PDB.PDBIO" instead

"PDBParser" is not exported from module "Bio.PDB"
  Import from "Bio.PDB.PDBParser" instead

"Select" is not exported from module "Bio.PDB"
  Import from "Bio.PDB.PDBIO" instead
```

## Workaround

Manually adding the `site-packages` path to `extraPaths` in `pyproject.toml` resolves the issue:

```toml
extraPaths = [".venv/lib/python3.10/site-packages"]
```

However, this should not be necessary, as the site-packages directory is part of the interpreter’s sys.path and should be detected automatically.

## Additional notes

- This is **not** a multi-root workspace.
- The interpreter is correctly selected via `Python: Select Interpreter`.
- I’ve reviewed [Issue #6669](https://github.com/microsoft/pylance-release/issues/6669), but that case involves multiple virtual environments and a more complex multi-root setup. My case is simpler and easier to reproduce.
- Pyright CLI also fails to resolve the import unless `extraPaths` is set explicitly.
